<?php


/**
* @file
* Random Taxonomy Term Module File
*
* This module allows site administrators to display a number of terms
* randomly in a block.  
*/


/**
* Implements hook_help().
*/
function random_taxonomy_term_help($path, $arg) {
  if ($path == 'admin/help#random_taxonomy_term') {
  	return t('Random Taxonomy Term allows site administrators the ability to randomly display taxonomy terms from a configurable vocabulary.');
  }
}


/**
 * Implements hook_permission().
 */
function random_taxonomy_term_permission() {
  return array(
    'administer random taxonomy terms' => array(
      'title' => t('Administer Random Taxonomy Terms'),
      'description' => t('Set a configurable vocabulary to pull out random terms to appear in a block.'),
    ),
  );
}


/**
* Implements hook_menu().
*/
function random_taxonomy_term_menu() {
  $items = array();
  $items['admin/config/user-interface/random_taxonomy_term'] = array(
    'title' => 'Random Taxonomy Term',
    'description' => 'Configuration for the Random Taxonomy Term module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('random_taxonomy_term_form'),
    'access arguments' => array('administer random taxonomy terms'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
*  Form Builder: Create and display the Random Taxonomy Term configuration settings form.
*/
function random_taxonomy_term_form($form, &$form_state) {
  // Vocabulary to pull random terms from
  $form['random_taxonomy_term_vocabulary'] = array(
    '#type' =>'select',
    '#title' => t('Vocabulary'),
    '#default_value' => variable_get('random_taxonomy_term_vocabulary', ''),
    '#options' => random_taxonomy_term_vocabularies(),
    '#description' => t('the vocabulary from which to pull random terms'),
    '#required' => TRUE,
  );
  $form['random_taxonomy_term_sorting'] = array(
    '#type' =>'select',
    '#title' => t('Sorting'),
    '#default_value' => variable_get('random_taxonomy_term_sorting', 'Ascending'),
    '#options' => array(
      0 => t('Ascending'),
      1 => t('Descending'),
      2 => t('Random'),
    ),
    '#description' => t('how to sort the terms'),
    '#required' => TRUE,
  );
  // Number of Terms to Pull-Out and Display
  $form['random_taxonomy_term_number'] = array(
    '#type' => 'select',
    '#default_value' => variable_get('random_taxonomy_term_number'),
    '#title' => t('Number of Terms'),
    '#options' => array(
      0 => t('1'),
      1 => t('2'),
      2 => t('3'),
      3 => t('4'),
      4 => t('5'),
      5 => t('6'),
      6 => t('7'),
      7 => t('8'),
      8 => t('9'),
      9 => t('10'),
    ),
    '#required' => TRUE,
    '#description' => t('The number of terms to randomly pull out and display.'),
  );
  return system_settings_form($form);
}


//Returns an array of all vocabularies.  Used in select list in configuration form.
function random_taxonomy_term_vocabularies() {
  $sql = "SELECT vid, name FROM {taxonomy_vocabulary}";
  $result = db_query($sql);
  $random_taxonomy_vocabularies = array();
  
  if ($result) {
    while ($row = $result->fetchAssoc()) {
      $key = $row['vid'];
      $value = $row['name'];
      $random_taxonomy_vocabularies[$key] = $value;
    }
    return $random_taxonomy_vocabularies;
  } else {
  	return FALSE;
  }
}


/**
* Implements hook_block_info().
*/
function random_taxonomy_term_block_info() {
  $blocks = array();
  $blocks['random_taxonomy_terms'] = array(
    'info' => t('Random Taxonomy Terms'),
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 * 
 * @param $delta
 * The name of the requested block.
 */
function random_taxonomy_term_block_view($delta = '') {
  //Create an empty block
  $block = array(
    'subject' => '',
    'content' => '',
  );
  //Check which block is being requested
  switch ($delta) {
    case 'random_taxonomy_terms':
      $raw_terms = random_taxonomy_term_terms_final();
      $formatted_terms = theme('item_list', $raw_terms);
      $block['content'] = $formatted_terms;
  }
 
  return $block;
}


//Returns an array of all terms that match the selected vocabulary.  Used in select list in configuration form.
function random_taxonomy_term_all_terms() {
  $selected_vocabulary = variable_get('random_taxonomy_term_vocabulary');
  //Pull out the vid
  $vid_result = db_query("SELECT vid FROM {taxonomy_vocabulary} WHERE name = :vocabulary", array(':vocabulary' => $selected_vocabulary));
  if ($vid_result) {
    while ($vid_row = $vid_result->fetchAssoc()) {
      $vid = $row['vid'];
    }
    $terms_result = db_query("SELECT name FROM {taxonomy_term_data} WHERE vid = :vid", array(':vid' => $vid));
    while ($terms_row = $terms_result->fetchAssoc()) {
      $terms = $terms_row['name'];
    }
    return $terms;
  }
  else {
    return FALSE;
  }
}


//Randomly pulls out a given number of terms, and sorts them based on the admin's choice
function random_taxonomy_term_terms_final() {
  $terms = random_taxonomy_term_all_terms();
  $number_terms = variable_get('random_taxonomy_term_number');
  $random_terms = array_rand($terms, $number_terms);
  $sort_order = variable_get('random_taxonomy_term_sorting');
  if ($sort_order == 'Ascending') {
    return sort($random_terms);
  }
  if ($sort_order == 'Descending') {
    return array_reverse(sort($random_terms));
  }
  else {
    return shuffle($random_terms);
  }
}












